[package]
name = "interactive-file-mover"
version = "0.1.0"
edition = "2021"
rust-version = "1.73.0"

[[bin]]
name="server"
path="src/server.rs"

[[bin]]
name="test"
path="src/test.rs"

[dependencies]
warp = "0.3.5"
serde = {version="1.0.171",features=["derive"]}
serde_yaml = "0.9.22"
thiserror = "1.0.43"
pretty_env_logger = "0.5.0"
log = "0.4.19"
serde_json = "1.0.101"
glob = "0.3.1"
tokio = {version="1.29.1",features=["full"]}
